vich_uploader:
    db_driver: orm

    mappings:
        produits:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/produits'
            

        media_object:
            uri_prefix: /media
            upload_destination: '%kernel.project_dir%/public/media'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer